SELECT * FROM [Budget-Track].[dbo].tUser;
SELECT * FROM [Budget-Track].[dbo].tRole;
SELECT * FROM [Budget-Track].[dbo].tDepartment;
SELECT * FROM [Budget-Track].[dbo].tCategory;
SELECT * FROM [Budget-Track].[dbo].tBudget;
SELECT * FROM [Budget-Track].[dbo].tExpense;
SELECT * FROM [Budget-Track].[dbo].tAuditLog;
SELECT * FROM [Budget-Track].[dbo].tNotification;
SELECT * FROM [Budget-Track].[dbo].tReport;